"""
    sitreps

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import sitreps_python_api
from sitreps_python_api.api.projects_api import ProjectsApi  # noqa: E501


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self):
        self.api = ProjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_project(self):
        """Test case for create_project

        Create Project  # noqa: E501
        """
        pass

    def test_delete_project(self):
        """Test case for delete_project

        Delete Project  # noqa: E501
        """
        pass

    def test_read_project(self):
        """Test case for read_project

        Read Project  # noqa: E501
        """
        pass

    def test_read_project_id(self):
        """Test case for read_project_id

        Read Project Id  # noqa: E501
        """
        pass

    def test_update_project(self):
        """Test case for update_project

        Update Project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
