"""
    sitreps

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sitreps_python_api
from sitreps_python_api.model.integration_test_create import IntegrationTestCreate


class TestIntegrationTestCreate(unittest.TestCase):
    """IntegrationTestCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIntegrationTestCreate(self):
        """Test IntegrationTestCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IntegrationTestCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
