"""
    sitreps

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import sitreps_python_api
from sitreps_python_api.api.sonar_qube_api import SonarQubeApi  # noqa: E501


class TestSonarQubeApi(unittest.TestCase):
    """SonarQubeApi unit test stubs"""

    def setUp(self):
        self.api = SonarQubeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_sonarqube(self):
        """Test case for create_sonarqube

        Create Sonarqube  # noqa: E501
        """
        pass

    def test_read_sonarqube(self):
        """Test case for read_sonarqube

        Read Sonarqube  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
