"""
    sitreps

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sitreps_python_api
from sitreps_python_api.model.repository_create import RepositoryCreate


class TestRepositoryCreate(unittest.TestCase):
    """RepositoryCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepositoryCreate(self):
        """Test RepositoryCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RepositoryCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
