"""
    sitreps

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sitreps_python_api
from sitreps_python_api.model.repository_update import RepositoryUpdate


class TestRepositoryUpdate(unittest.TestCase):
    """RepositoryUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepositoryUpdate(self):
        """Test RepositoryUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RepositoryUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
