"""
    sitreps

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import sitreps_python_api
from sitreps_python_api.api.project_groups_api import ProjectGroupsApi  # noqa: E501


class TestProjectGroupsApi(unittest.TestCase):
    """ProjectGroupsApi unit test stubs"""

    def setUp(self):
        self.api = ProjectGroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_project_group(self):
        """Test case for create_project_group

        Create Project Group  # noqa: E501
        """
        pass

    def test_delete_project_group(self):
        """Test case for delete_project_group

        Delete Project Group  # noqa: E501
        """
        pass

    def test_read_project_group(self):
        """Test case for read_project_group

        Read Project Group  # noqa: E501
        """
        pass

    def test_read_project_groups(self):
        """Test case for read_project_groups

        Read Project Groups  # noqa: E501
        """
        pass

    def test_update_project_group(self):
        """Test case for update_project_group

        Update Project Group  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
