"""
    sitreps

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import sitreps_python_api
from sitreps_python_api.api.count_line_of_code_api import CountLineOfCodeApi  # noqa: E501


class TestCountLineOfCodeApi(unittest.TestCase):
    """CountLineOfCodeApi unit test stubs"""

    def setUp(self):
        self.api = CountLineOfCodeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_cloc(self):
        """Test case for create_cloc

        Create Cloc  # noqa: E501
        """
        pass

    def test_read_cloc(self):
        """Test case for read_cloc

        Read Cloc  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
