"""
    sitreps

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import sitreps_python_api
from sitreps_python_api.api.metadata_api import MetadataApi  # noqa: E501


class TestMetadataApi(unittest.TestCase):
    """MetadataApi unit test stubs"""

    def setUp(self):
        self.api = MetadataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_metadata(self):
        """Test case for create_metadata

        Create Metadata  # noqa: E501
        """
        pass

    def test_read_metadata(self):
        """Test case for read_metadata

        Read Metadata  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
