"""
    sitreps

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sitreps_python_api
from sitreps_python_api.model.unit_test_create import UnitTestCreate


class TestUnitTestCreate(unittest.TestCase):
    """UnitTestCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnitTestCreate(self):
        """Test UnitTestCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UnitTestCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
