"""
    sitreps

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import sitreps_python_api
from sitreps_python_api.api.integration_tests_api import IntegrationTestsApi  # noqa: E501


class TestIntegrationTestsApi(unittest.TestCase):
    """IntegrationTestsApi unit test stubs"""

    def setUp(self):
        self.api = IntegrationTestsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_integration_test(self):
        """Test case for create_integration_test

        Create Integration Test  # noqa: E501
        """
        pass

    def test_read_integration_test(self):
        """Test case for read_integration_test

        Read Integration Test  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
