"""
    sitreps

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import sitreps_python_api
from sitreps_python_api.api.jira_api import JiraApi  # noqa: E501


class TestJiraApi(unittest.TestCase):
    """JiraApi unit test stubs"""

    def setUp(self):
        self.api = JiraApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_jira(self):
        """Test case for create_jira

        Create Jira  # noqa: E501
        """
        pass

    def test_read_jira(self):
        """Test case for read_jira

        Read Jira  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
