"""
    sitreps

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sitreps_python_api
from sitreps_python_api.model.sonar_qube_create import SonarQubeCreate


class TestSonarQubeCreate(unittest.TestCase):
    """SonarQubeCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSonarQubeCreate(self):
        """Test SonarQubeCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SonarQubeCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
