"""
    sitreps

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import sitreps_python_api
from sitreps_python_api.api.repositories_api import RepositoriesApi  # noqa: E501


class TestRepositoriesApi(unittest.TestCase):
    """RepositoriesApi unit test stubs"""

    def setUp(self):
        self.api = RepositoriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_repository(self):
        """Test case for create_repository

        Create Repository  # noqa: E501
        """
        pass

    def test_delete_repository(self):
        """Test case for delete_repository

        Delete Repository  # noqa: E501
        """
        pass

    def test_read_repository(self):
        """Test case for read_repository

        Read Repository  # noqa: E501
        """
        pass

    def test_read_repository_id(self):
        """Test case for read_repository_id

        Read Repository Id  # noqa: E501
        """
        pass

    def test_update_repository(self):
        """Test case for update_repository

        Update Repository  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
