"""
    sitreps

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import sitreps_python_api
from sitreps_python_api.api.unit_tests_api import UnitTestsApi  # noqa: E501


class TestUnitTestsApi(unittest.TestCase):
    """UnitTestsApi unit test stubs"""

    def setUp(self):
        self.api = UnitTestsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_unittests(self):
        """Test case for create_unittests

        Create Unittests  # noqa: E501
        """
        pass

    def test_read_unittests(self):
        """Test case for read_unittests

        Read Unittests  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
